#ifndef MUSTANG_SENSOR_PARAMS_H
#define MUSTANG_SENSOR_PARAMS_H

/*****************************************************************************
* Sensor parameters - used by SensorDriver and OsloSensorPlugin
****************************************************************************/
#define SOLI_PRESET_CONFIG_START_INDEX  100
#define SOLI_CONTROL_START_INDEX        200
#define SOLI_RADAR_SETTING_START_INDEX  300
#define SOLI_REGISTER_RW_START_INDEX    400

typedef enum
{
    SENSOR_PARAM_INVALID = 0,
    SENSOR_PARAM_SAMP_RATE_UNUSED,
    SENSOR_PARAM_SAMP_SIZE_UNUSED,
    SENSOR_PARAM_INTF_SPEED_UNUSED,
    SENSOR_PARAM_DRIVER_STATE,
    SENSOR_PARAM_FRAMES_PROCESSED,
    SENSOR_PARAM_WATCHDOG_RECOVERY_COUNT,
    SENSOR_PARAM_PRESET_RADAR_CONFIG,
    SENSOR_PARAM_DUMP_STATS,
    SENSOR_PARAM_IS_RADAR_OPENED_SUCCESSFULLY,

    /* soli preset configurations */
    SOLI_CONFIG_DEFAULT = SOLI_PRESET_CONFIG_START_INDEX,
    SOLI_CONFIG_PRESENCE,
    SOLI_CONFIG_CONTINUOUS,
    SOLI_CONFIG_PRESENCE_SLOW,
    SOLI_CONFIG_FACTORY_PRESENCE,
    SOLI_CONFIG_FACTORY_REACH,
    SOLI_CONFIG_CW_MODE,
    SOLI_CONFIG_IDLE,
    SOLI_CONFIG_FACTORY_PRESENCE_V1,
    SOLI_CONFIG_FACTORY_REACH_V1,
    SOLI_CONFIG_REACH,
    SOLI_CONFIG_PRESENCE_V1,
    SOLI_CONFIG_REACH_V1,
    SOLI_CONFIG_OFF,
    SOLI_CONFIG_TEST,

    /* soli radar control - restart radar when settings change */
    SOLI_RADAR_CONTROL_RESTART = SOLI_CONTROL_START_INDEX,
    SOLI_RADAR_CONTROL_STRIP_HEADERS,
    SOLI_RADAR_CONTROL_SLPI_INT,
    SOLI_RADAR_CONTROL_STOP,
    SOLI_RADAR_CONTROL_SIMULATE_RADAR_DATA,
    SOLI_RADAR_CONTROL_INJECT_RADAR_DATA,
    SOLI_RADAR_CONTROL_INJECT_FRAME_READY,
    SOLI_RADAR_CONTROL_ASSERT_RESET,
    SOLI_RADAR_CONTROL_DELAYED_START,

    /* soli radar settings */
    SOLI_PARAM_REQUEST_RATE = SOLI_RADAR_SETTING_START_INDEX,
    SOLI_PARAM_REQUEST_ANTENNA_MASK,
    SOLI_PARAM_TX_POWER,
    SOLI_PARAM_LOWER_FREQ,
    SOLI_PARAM_UPPER_FREQ,
    SOLI_PARAM_SAMPLES_PER_CHIRP,
    SOLI_PARAM_VGA_GAIN_CH1,
    SOLI_PARAM_VGA_GAIN_CH2,
    SOLI_PARAM_VGA_GAIN_CH3,
    SOLI_PARAM_VGA_GAIN_CH4,
    SOLI_PARAM_BURST_CHIRP_COUNT,
    SOLI_PARAM_BURST_CHIRP_RATE,
    SOLI_PARAM_BURST_POWER_MODE,
    SOLI_PARAM_BURST_INTERCHIRP_POWER_MODE,
    SOLI_PARAM_STARTUP_TIMING_WAKE_UP_TIME_100NS,
    SOLI_PARAM_STARTUP_TIMING_PLL_SETTLE_TIME_COARSE_100NS,
    SOLI_PARAM_STARTUP_TIMING_PLL_SETTLE_TIME_FINE_100NS,
    SOLI_PARAM_STARTUP_TIMING_OSCILLATOR_USEC,
    SOLI_PARAM_PRE_CHIRP_DELAY_100NS,
    SOLI_PARAM_POST_CHIRP_DELAY_100NS,
    SOLI_PARAM_CHIRP_PA_DELAY_100NS,
    SOLI_PARAM_CHIRP_ADC_DELAY_100NS,
    SOLI_PARAM_VISUALIZER_DATA_TYPE,
    SOLI_PARAM_OSCILLATOR_MODE,
    SOLI_PARAM_HP_GAIN_CH1,
    SOLI_PARAM_HP_GAIN_CH2,
    SOLI_PARAM_HP_GAIN_CH3,
    SOLI_PARAM_HP_GAIN_CH4,
    SOLI_PARAM_BASEBAND_RESET_PERIOD_1NS,
    SOLI_PARAM_HP_CUTOFF_CH1,
    SOLI_PARAM_HP_CUTOFF_CH2,
    SOLI_PARAM_HP_CUTOFF_CH3,
    SOLI_PARAM_HP_CUTOFF_CH4,
    SOLI_PARAM_PHASE_CONFIG,
    SOLI_PARAM_IDLE_SETTINGS_ENABLE_PLL,
    SOLI_PARAM_IDLE_SETTINGS_ENABLE_VCO,
    SOLI_PARAM_IDLE_SETTINGS_ENABLE_FDIV,
    SOLI_PARAM_IDLE_SETTINGS_ENABLE_BASEBAND,
    SOLI_PARAM_IDLE_SETTINGS_ENABLE_RF,
    SOLI_PARAM_IDLE_SETTINGS_ENABLE_MADC,
    SOLI_PARAM_IDLE_SETTINGS_ENABLE_MADC_BANDGAP,
    SOLI_PARAM_IDLE_SETTINGS_ENABLE_SADC,
    SOLI_PARAM_IDLE_SETTINGS_ENABLE_SADC_BANDGAP,
    SOLI_PARAM_DEEP_SLEEP_SETTINGS_ENABLE_PLL,
    SOLI_PARAM_DEEP_SLEEP_SETTINGS_ENABLE_VCO,
    SOLI_PARAM_DEEP_SLEEP_SETTINGS_ENABLE_FDIV,
    SOLI_PARAM_DEEP_SLEEP_SETTINGS_ENABLE_BASEBAND,
    SOLI_PARAM_DEEP_SLEEP_SETTINGS_ENABLE_RF,
    SOLI_PARAM_DEEP_SLEEP_SETTINGS_ENABLE_MADC,
    SOLI_PARAM_DEEP_SLEEP_SETTINGS_ENABLE_MADC_BANDGAP,
    SOLI_PARAM_DEEP_SLEEP_SETTINGS_ENABLE_SADC,
    SOLI_PARAM_DEEP_SLEEP_SETTINGS_ENABLE_SADC_BANDGAP,
    SOLI_PARAM_TOSS_COUNT,
    SOLI_PARAM_CHIRP_DIRECTION,
    SOLI_PARAM_ADC_SAMPLE_RATE,
    SOLI_PARAM_CHARGE_PUMP,
    SOLI_PARAM_MAX_TX_POWER,

    /* soli register r/w */
    SOLI_REGISTER_MIN = SOLI_REGISTER_RW_START_INDEX,
    SOLI_REGISTER_MAX = SOLI_REGISTER_RW_START_INDEX + 99,

    SENSOR_PARAM_NUM,
} SensorParam;

#endif  // MUSTANG_SENSOR_PARAMS_H
